server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:search

logging:
  level:
    root: INFO
    com.api.demo : DEBUG

api:
  kakao-url:  https://dapi.kakao.com/v2/search/blog
  kakao-authKey: KakaoAK 9a2a8c4c441f391e4d98364cea2b8edb
  naver-url: https://openapi.naver.com/v1/search/blog.json
